### ISSUE TITLE
Notes and Images not loading in v1.1.1

### ISSUE THREAD

**Issue by mcnasty-coder** [pixelomer/mobilegoose#1]
Since updating to v1.1.1, the notes and images MobileGoose brings just say error loading note/image. Downgrading to v1.1 foxes this. 
![5659C100-8562-4922-BF42-9103A22B039A](https://user-images.githubusercontent.com/61098854/74767251-7f053680-5254-11ea-8159-68f7bec1c315.png)
![08B3B294-ECD9-48EF-AFE4-9E5016F24D98](https://user-images.githubusercontent.com/61098854/74767260-875d7180-5254-11ea-88bf-a02308f42a4d.png)

**Comment by pixelomer** [comment]
Fixed with ba39cc1. The fix was released as v1.1.2, but v1.1.2 was never pushed to this repository. Instead, v1.1.2 changes were pushed alongside v1.2 changes.
